### ISSUE TITLE
How to implement hot swap?

### ISSUE THREAD

**Issue by guoguo338** [Instagram/ig-lazy-module-loader#2]
"module hotswapping may be implemented allowing for faster development without restarting the app"。For example, Class A and Class B exists in the same module, and Class A calls Class B, at some time, Class A instance instanceA is created and remained in cache, then developer changed Class B to Class B2,  instanceA would call Class B2, there would be compatibility issue, correct?

**Comment by juliankrz** [comment]
Yes you're right - this could lead to compatibility issue. To un-cache a class - the class loader responsible for loading that class needs to be dropped - my library does not include the actual implementation of how we did this (we might be able to open source it in the future). To give you a brief description: one way to work around the caching issue is to implement a class loader which would contain a list of class loaders (e.g. DexClassLoaders) - each of those class loaders would load a single dex file. Once you want to hotswap the module you would need to drop its class loader and replace it with a new one. I hope it helps. Thanks for raising this!

**Comment by asp2insp** [comment]
@guoguo338 We've just begun open-sourcing support for hotswapping via Buck. More detailed docs and tutorials are coming soon, but if you'd like to get started today, you can see an implementation of a ClassLoader which provides the functionality that Julian mentioned in the buck support lib: https://github.com/facebook/buck/blob/master/android/com/facebook/buck/android/support/exopackage/DelegatingClassLoader.java
